<?php

/**
 * Debug Bar: tab "time" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;
?>
<span title="Execution time">
	<span class="tracy-debug-bar-icon">
		<?php readfile(__DIR__ . '/icons/clock-o.svg') ?>
	</span>
	<?php echo number_format((microtime(TRUE) - Debugger::$time) * 1000, 1, '.', ' ') ?> ms
</span>
